spring.application.name=heranca-spring
server.port= 8888
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-heranca

spring.datasource.username=postgres
spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

resilience4j.circuitbreaker.configs.default.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.configs.default.sliding-window-size=3
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=3

# Abre o circuito se 2 das 3 chamadas falharem (66%)
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50

# Não considerar chamadas lentas
resilience4j.circuitbreaker.configs.default.slow-call-rate-threshold=100
resilience4j.circuitbreaker.configs.default.slow-call-duration-threshold=60000

# Fica aberto por 10 segundos
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10000

# Testa apenas 1 chamada no HALF_OPEN
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=1

resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.configs.default.register-health-indicator=true